from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    STATUS_CHOICES = [
        ('excellent', 'Excellent'),
        ('very good', 'Very Good'),
        ('satisfactory', 'Satisfactory'),
        ('needs improvement', 'Needs Improvement'),
    ]
    st_6 = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=STATUS_CHOICES,
        label="How is it going?",
    )

    class Meta:
        model = Post
        fields = ('coordinator',
                  'is_complete',
                  'date_of_contact',
                  'student_surname',
                  'hostfamily',
                  'student_eng_name',
                  'st_1',
                  'st_1a',
                  'st_2',
                  'st_3',
                  'st_4',
                  'st_4a',
                  'st_4b',
                  'st_5',
                  'st_5a',
                  'st_6',
                  'st_6a',
                  'st_6b',
                  'st_7',
                  'st_7a',
                  'st_7b',
                  'st_coordinator_comments',
                  # Host Family Progress Report
                  'hf_hostfamily_name',
                  'hf_1',
                  'hf_1a',
                  'hf_2',
                  'hf_3',
                  'hf_3a',
                  'hf_3b',
                  'hf_4',
                  'hf_4a',
                  'hf_4b',
                  'hf_5',
                  'hf_5a',
                  'hf_6',
                  'hf_6a',
                  'hf_7',
                  'hf_7a',
                  'hf_coordinator_comments',
                  # School Progress Report
                  'sch_school_name',
                  'sch_student_name',
                  'sch_1a',
                  'sch_1b',
                  'sch_2',
                  'sch_2a',
                  'sch_3',
                  'sch_3a',
                  'sch_4',
                  'sch_4a',
                  'sch_4b',
                  'sch_4c',
                  'sch_5',
                  'sch_5a',
                  'sch_6',
                  'sch_classes_grades',
                  'photo_main')
        labels = {
            "coordinator": "Coordinator's Name",
            "date_of_contact": "Date(s) of contact (Month/Day/Year):",
            "student_surname": "Student's Surname, Given Name:",
            "hostfamily": "Host Family Name",
            "student_eng_name": "Student's English Name",
            "st_1": "* How are you getting along with your host family?",
            "st_1a": "Comments:",
            "st_2": "Please Tell me about an experience you had this month at school that differs from last month (REQUIRED).",
            "st_3": "Please Tell me about an experience you had this month with your host family that differs from last month (REQUIRED).",
            "st_4": "* Do you feel you are improving your conversational english?",
            "st_4a": "If yes, provide examples of how you have improved your conversational level of English:",
            "st_4b": "If no, provide examples of areas you would like to improve upon to help strengthen your level of English:",
            "st_5": "* Have you made new American friends & interests in the community or school?",
            "st_5a": "If yes, provide details:",
            "st_6": "* How do you feel you are doing in school?",
            "st_6a": "What is your favorite subject this month?",
            "st_6b": "What subject are you having trouble with this month?",
            "st_7": "* Did you experience any issues this month with your host family or at School?",
            "st_7a": "Is there anything you would like to talk about or need help with?",
            "st_7b": "Student's Comments:",
            "st_coordinator_comments": "Coordinator's comments re: Student's progress this month (REQUIRED):",
            "hf_hostfamily_name": "HOST FAMILY'S LAST NAME",
            "hf_1": "How is your relationship with your student?",
            "hf_1a": "Comments:",
            "hf_2": "Please Tell me about an experience you had this month with your student that differs from last month (REQUIRED).",
            "hf_3": "* Do you feel your student is improving his/her level of conversational english?",
            "hf_3a": "If yes, provide examples of how your student has improved in this area:",
            "hf_3b": "If no, provide examples of specific areas you feel your student can improve upon to help strengthen his/her level of English:",
            "hf_4": "Has your student interacted with your family this month?",
            "hf_4a": "If yes, provide examples of how your student interacted with your family this month:",
            "hf_4b": "If no, provide examples of how your student can better interact with your family:",
            "hf_5": "Has your student made plans with any American friends or shown any interest in events in the community?",
            "hf_5a": "If yes, please provide details:",
            "hf_6": "Does your student obey the rules at home this month?",
            "hf_6a": "If no, please provide details so MAH can counsel the student to better improve in this area:",
            "hf_7": "Rate your hosting experience so far:",
            "hf_7a": "Host Family's Comments:",
            "hf_coordinator_comments": "Coordinator's comments re: Host Family progress this month (REQUIRED):",
            "sch_school_name": "School's Name",
            "sch_student_name": "Student's Name",
            "sch_1a": "School Contact's Name:",
            "sch_1b": "School Contact's Title",
            "sch_2": "What is the school's impression of the student's academic performance this month?",
            "sch_2a": "School's feedback about student's academic performance this month:",
            "sch_3": "Has the student had any accomplishments (e.g., honor roll, athletics, club participation)?",
            "sch_3a": "Please list details re: accomplishments:",
            "sch_4": "Has the student missed any days from school",
            "sch_4a": "# of Days Missed",
            "sch_4b": "Were these excused absences?",
            "sch_4c": "School's Comments re: student's attendance:",
            "sch_5": "Does the student need additional help at school, such as tutoring, or is there any area(s) MAH can counsel the student to help him/her improve in this area?",
            "sch_5a": "School's Comments re:",
            "sch_6": "Is the student receiving a 'C' or better in each class?",
            "sch_classes_grades": "List all classes & current grades this month below.",
            "photo_main": "Add Student Photo"
        }
        widgets = {
            "coordinator": forms.TextInput(attrs={"class": "form-control"}),
            # "st_1": forms.Select(attrs={"choices": "STATUS_CHOICES"}),
            'st_1a': forms.Textarea(attrs={'cols': 150, 'rows': 5}),
            'date_of_contact': forms.SelectDateWidget()
        }

    # class Meta:
    #     model = Post
    #     fields = ('coordinator',
    #               'is_complete',
    #               'date_of_contact',
    #               'student_surname',
    #               'hostfamily',
    #               'student_eng_name',
    #               'st_1',
    #               'st_1a',
    #               'st_2',
    #               'st_3',
    #               'st_4',
    #               'st_4a',
    #               'st_4b',
    #               'st_5',
    #               'st_5a',
    #               'st_6',
    #               'st_6a',
    #               'st_6b',
    #               'st_7',
    #               'st_7a',
    #               'st_7b',
    #               'st_coordinator_comments',
    #               # Host Family Progress Report
    #               'hf_hostfamily_name',
    #               'hf_1',
    #               'hf_1a',
    #               'hf_2',
    #               'hf_3',
    #               'hf_3a',
    #               'hf_3b',
    #               'hf_4',
    #               'hf_4a',
    #               'hf_4b',
    #               'hf_5',
    #               'hf_5a',
    #               'hf_6',
    #               'hf_6a',
    #               'hf_7',
    #               'hf_7a',
    #               'hf_coordinator_comments',
    #               # School Progress Report
    #               'sch_school_name',
    #               'sch_student_name',
    #               'sch_1a',
    #               'sch_1b',
    #               'sch_2',
    #               'sch_2a',
    #               'sch_3',
    #               'sch_3a',
    #               'sch_4',
    #               'sch_4a',
    #               'sch_4b',
    #               'sch_4c',
    #               'sch_5',
    #               'sch_5a',
    #               'sch_6',
    #               'sch_classes_grades',
    #               'photo_main',
    #               )
